// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"sync"

	"code.cloudfoundry.org/korifi/controllers/controllers/services/osbapi"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type AssetsClientFactory struct {
	CreateAssetsClientStub        func(client.Client, string) osbapi.AssetsClient
	createAssetsClientMutex       sync.RWMutex
	createAssetsClientArgsForCall []struct {
		arg1 client.Client
		arg2 string
	}
	createAssetsClientReturns struct {
		result1 osbapi.AssetsClient
	}
	createAssetsClientReturnsOnCall map[int]struct {
		result1 osbapi.AssetsClient
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *AssetsClientFactory) CreateAssetsClient(arg1 client.Client, arg2 string) osbapi.AssetsClient {
	fake.createAssetsClientMutex.Lock()
	ret, specificReturn := fake.createAssetsClientReturnsOnCall[len(fake.createAssetsClientArgsForCall)]
	fake.createAssetsClientArgsForCall = append(fake.createAssetsClientArgsForCall, struct {
		arg1 client.Client
		arg2 string
	}{arg1, arg2})
	stub := fake.CreateAssetsClientStub
	fakeReturns := fake.createAssetsClientReturns
	fake.recordInvocation("CreateAssetsClient", []interface{}{arg1, arg2})
	fake.createAssetsClientMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *AssetsClientFactory) CreateAssetsClientCallCount() int {
	fake.createAssetsClientMutex.RLock()
	defer fake.createAssetsClientMutex.RUnlock()
	return len(fake.createAssetsClientArgsForCall)
}

func (fake *AssetsClientFactory) CreateAssetsClientCalls(stub func(client.Client, string) osbapi.AssetsClient) {
	fake.createAssetsClientMutex.Lock()
	defer fake.createAssetsClientMutex.Unlock()
	fake.CreateAssetsClientStub = stub
}

func (fake *AssetsClientFactory) CreateAssetsClientArgsForCall(i int) (client.Client, string) {
	fake.createAssetsClientMutex.RLock()
	defer fake.createAssetsClientMutex.RUnlock()
	argsForCall := fake.createAssetsClientArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *AssetsClientFactory) CreateAssetsClientReturns(result1 osbapi.AssetsClient) {
	fake.createAssetsClientMutex.Lock()
	defer fake.createAssetsClientMutex.Unlock()
	fake.CreateAssetsClientStub = nil
	fake.createAssetsClientReturns = struct {
		result1 osbapi.AssetsClient
	}{result1}
}

func (fake *AssetsClientFactory) CreateAssetsClientReturnsOnCall(i int, result1 osbapi.AssetsClient) {
	fake.createAssetsClientMutex.Lock()
	defer fake.createAssetsClientMutex.Unlock()
	fake.CreateAssetsClientStub = nil
	if fake.createAssetsClientReturnsOnCall == nil {
		fake.createAssetsClientReturnsOnCall = make(map[int]struct {
			result1 osbapi.AssetsClient
		})
	}
	fake.createAssetsClientReturnsOnCall[i] = struct {
		result1 osbapi.AssetsClient
	}{result1}
}

func (fake *AssetsClientFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createAssetsClientMutex.RLock()
	defer fake.createAssetsClientMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *AssetsClientFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ osbapi.AssetsClientFactory = new(AssetsClientFactory)
