// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	"code.cloudfoundry.org/korifi/controllers/api/v1alpha1"
	"code.cloudfoundry.org/korifi/controllers/controllers/services/osbapi"
)

type AssetsClient struct {
	GetServiceBindingAssetsStub        func(context.Context, *v1alpha1.CFServiceBinding) (osbapi.ServiceBindingAssets, error)
	getServiceBindingAssetsMutex       sync.RWMutex
	getServiceBindingAssetsArgsForCall []struct {
		arg1 context.Context
		arg2 *v1alpha1.CFServiceBinding
	}
	getServiceBindingAssetsReturns struct {
		result1 osbapi.ServiceBindingAssets
		result2 error
	}
	getServiceBindingAssetsReturnsOnCall map[int]struct {
		result1 osbapi.ServiceBindingAssets
		result2 error
	}
	GetServiceInstanceAssetsStub        func(context.Context, *v1alpha1.CFServiceInstance) (osbapi.ServiceInstanceAssets, error)
	getServiceInstanceAssetsMutex       sync.RWMutex
	getServiceInstanceAssetsArgsForCall []struct {
		arg1 context.Context
		arg2 *v1alpha1.CFServiceInstance
	}
	getServiceInstanceAssetsReturns struct {
		result1 osbapi.ServiceInstanceAssets
		result2 error
	}
	getServiceInstanceAssetsReturnsOnCall map[int]struct {
		result1 osbapi.ServiceInstanceAssets
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *AssetsClient) GetServiceBindingAssets(arg1 context.Context, arg2 *v1alpha1.CFServiceBinding) (osbapi.ServiceBindingAssets, error) {
	fake.getServiceBindingAssetsMutex.Lock()
	ret, specificReturn := fake.getServiceBindingAssetsReturnsOnCall[len(fake.getServiceBindingAssetsArgsForCall)]
	fake.getServiceBindingAssetsArgsForCall = append(fake.getServiceBindingAssetsArgsForCall, struct {
		arg1 context.Context
		arg2 *v1alpha1.CFServiceBinding
	}{arg1, arg2})
	stub := fake.GetServiceBindingAssetsStub
	fakeReturns := fake.getServiceBindingAssetsReturns
	fake.recordInvocation("GetServiceBindingAssets", []interface{}{arg1, arg2})
	fake.getServiceBindingAssetsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AssetsClient) GetServiceBindingAssetsCallCount() int {
	fake.getServiceBindingAssetsMutex.RLock()
	defer fake.getServiceBindingAssetsMutex.RUnlock()
	return len(fake.getServiceBindingAssetsArgsForCall)
}

func (fake *AssetsClient) GetServiceBindingAssetsCalls(stub func(context.Context, *v1alpha1.CFServiceBinding) (osbapi.ServiceBindingAssets, error)) {
	fake.getServiceBindingAssetsMutex.Lock()
	defer fake.getServiceBindingAssetsMutex.Unlock()
	fake.GetServiceBindingAssetsStub = stub
}

func (fake *AssetsClient) GetServiceBindingAssetsArgsForCall(i int) (context.Context, *v1alpha1.CFServiceBinding) {
	fake.getServiceBindingAssetsMutex.RLock()
	defer fake.getServiceBindingAssetsMutex.RUnlock()
	argsForCall := fake.getServiceBindingAssetsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *AssetsClient) GetServiceBindingAssetsReturns(result1 osbapi.ServiceBindingAssets, result2 error) {
	fake.getServiceBindingAssetsMutex.Lock()
	defer fake.getServiceBindingAssetsMutex.Unlock()
	fake.GetServiceBindingAssetsStub = nil
	fake.getServiceBindingAssetsReturns = struct {
		result1 osbapi.ServiceBindingAssets
		result2 error
	}{result1, result2}
}

func (fake *AssetsClient) GetServiceBindingAssetsReturnsOnCall(i int, result1 osbapi.ServiceBindingAssets, result2 error) {
	fake.getServiceBindingAssetsMutex.Lock()
	defer fake.getServiceBindingAssetsMutex.Unlock()
	fake.GetServiceBindingAssetsStub = nil
	if fake.getServiceBindingAssetsReturnsOnCall == nil {
		fake.getServiceBindingAssetsReturnsOnCall = make(map[int]struct {
			result1 osbapi.ServiceBindingAssets
			result2 error
		})
	}
	fake.getServiceBindingAssetsReturnsOnCall[i] = struct {
		result1 osbapi.ServiceBindingAssets
		result2 error
	}{result1, result2}
}

func (fake *AssetsClient) GetServiceInstanceAssets(arg1 context.Context, arg2 *v1alpha1.CFServiceInstance) (osbapi.ServiceInstanceAssets, error) {
	fake.getServiceInstanceAssetsMutex.Lock()
	ret, specificReturn := fake.getServiceInstanceAssetsReturnsOnCall[len(fake.getServiceInstanceAssetsArgsForCall)]
	fake.getServiceInstanceAssetsArgsForCall = append(fake.getServiceInstanceAssetsArgsForCall, struct {
		arg1 context.Context
		arg2 *v1alpha1.CFServiceInstance
	}{arg1, arg2})
	stub := fake.GetServiceInstanceAssetsStub
	fakeReturns := fake.getServiceInstanceAssetsReturns
	fake.recordInvocation("GetServiceInstanceAssets", []interface{}{arg1, arg2})
	fake.getServiceInstanceAssetsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AssetsClient) GetServiceInstanceAssetsCallCount() int {
	fake.getServiceInstanceAssetsMutex.RLock()
	defer fake.getServiceInstanceAssetsMutex.RUnlock()
	return len(fake.getServiceInstanceAssetsArgsForCall)
}

func (fake *AssetsClient) GetServiceInstanceAssetsCalls(stub func(context.Context, *v1alpha1.CFServiceInstance) (osbapi.ServiceInstanceAssets, error)) {
	fake.getServiceInstanceAssetsMutex.Lock()
	defer fake.getServiceInstanceAssetsMutex.Unlock()
	fake.GetServiceInstanceAssetsStub = stub
}

func (fake *AssetsClient) GetServiceInstanceAssetsArgsForCall(i int) (context.Context, *v1alpha1.CFServiceInstance) {
	fake.getServiceInstanceAssetsMutex.RLock()
	defer fake.getServiceInstanceAssetsMutex.RUnlock()
	argsForCall := fake.getServiceInstanceAssetsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *AssetsClient) GetServiceInstanceAssetsReturns(result1 osbapi.ServiceInstanceAssets, result2 error) {
	fake.getServiceInstanceAssetsMutex.Lock()
	defer fake.getServiceInstanceAssetsMutex.Unlock()
	fake.GetServiceInstanceAssetsStub = nil
	fake.getServiceInstanceAssetsReturns = struct {
		result1 osbapi.ServiceInstanceAssets
		result2 error
	}{result1, result2}
}

func (fake *AssetsClient) GetServiceInstanceAssetsReturnsOnCall(i int, result1 osbapi.ServiceInstanceAssets, result2 error) {
	fake.getServiceInstanceAssetsMutex.Lock()
	defer fake.getServiceInstanceAssetsMutex.Unlock()
	fake.GetServiceInstanceAssetsStub = nil
	if fake.getServiceInstanceAssetsReturnsOnCall == nil {
		fake.getServiceInstanceAssetsReturnsOnCall = make(map[int]struct {
			result1 osbapi.ServiceInstanceAssets
			result2 error
		})
	}
	fake.getServiceInstanceAssetsReturnsOnCall[i] = struct {
		result1 osbapi.ServiceInstanceAssets
		result2 error
	}{result1, result2}
}

func (fake *AssetsClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getServiceBindingAssetsMutex.RLock()
	defer fake.getServiceBindingAssetsMutex.RUnlock()
	fake.getServiceInstanceAssetsMutex.RLock()
	defer fake.getServiceInstanceAssetsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *AssetsClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ osbapi.AssetsClient = new(AssetsClient)
