---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: korifi-statefulset-runner-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Values.namespace }}/korifi-statefulset-runner-serving-cert'
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: korifi-statefulset-runner-webhook-service
        namespace: '{{ .Values.namespace }}'
        path: /mutate--v1-pod
    failurePolicy: Fail
    name: mstspod.korifi.cloudfoundry.org
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
    objectSelector:
      matchLabels:
        korifi.cloudfoundry.org/add-stsr-index: "true"
