global:
  rootNamespace: cf
  debug: false
  defaultAppDomainName: apps.my-cf-domain.com
  generateIngressCertificates: false
  packageRegistrySecret: image-registry-credentials

include: true
namespace: korifi-api-system
replicas: 1
resources:
  requests:
    cpu: 50m
    memory: 100Mi

apiServer:
  url: api.my-cf-domain.com # externalFQDN
  # To override default port, set port to a non-zero value
  port: 0
  internalPort: 9000
  timeouts:
    read: 900
    write: 900
    idle: 900
    readHeader: 10

image: cloudfoundry/korifi-api:latest

lifecycle:
  type: buildpack
  stack: cflinuxfs3
  stagingRequirements:
    memoryMB: 1024
    diskMB: 1024

builderName: kpack-image-builder
packageRegistry: registry-org/package-repo-name
userCertificateExpirationWarningDuration: 168h

authProxy:
  host:
  caCert:

