apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: korifi-job-task-runner
  name: korifi-job-task-runner-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: korifi-job-task-runner
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: korifi-job-task-runner
    spec:
      containers:
      - name: manager
{{- if .Values.global.debug }}
        command:
        - "/dlv"
        args:
        - "--listen=:40000"
        - "--headless=true"
        - "--api-version=2"
        - "exec"
        - "/manager"
        - "--continue"
        - "--accept-multiclient"
        - "--"
        - "--leader-elect"
{{- else }}
        args:
        - --leader-elect
{{- end }}
        env:
        - name: JOBTASKRUNNERCONFIG
          value: /etc/korifi-job-task-runner-config
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- include "korifi.resources" . | indent 8 }}
        {{- include "korifi.securityContext" . | indent 8 }}
        volumeMounts:
        - mountPath: /etc/korifi-job-task-runner-config
          name: korifi-job-task-runner-config
          readOnly: true
      serviceAccountName: korifi-job-task-runner-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: korifi-job-task-runner-config
        name: korifi-job-task-runner-config

