# permissions for end users to edit taskworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taskworkload-editor-role
rules:
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - taskworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - taskworkloads/status
  verbs:
  - get
