# permissions for end users to view taskworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taskworkload-viewer-role
rules:
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - taskworkloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - taskworkloads/status
  verbs:
  - get
