---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: system-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfapps
  - cfbuilds
  - cfpackages
  - cfprocesses
  - cfspaces
  - cftasks
  verbs:
  - list
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfdomains
  - cfroutes
  verbs:
  - list
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfservicebindings
  - cfserviceinstances
  verbs:
  - list
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
