# permissions for end users to edit builderinfos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: builderinfo-editor-role
rules:
- apiGroups:
  - korifi.cloudfoundry.org.cloudfoundry.org
  resources:
  - builderinfos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org.cloudfoundry.org
  resources:
  - builderinfos/status
  verbs:
  - get
