# permissions for end users to view builderInfoss.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: builderinfo-viewer-role
rules:
- apiGroups:
  - korifi.cloudfoundry.org.cloudfoundry.org
  resources:
  - builderinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - korifi.cloudfoundry.org.cloudfoundry.org
  resources:
  - builderinfos/status
  verbs:
  - get
