# permissions for end users to view cfspaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfspace-viewer-role
rules:
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfspaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfspaces/status
  verbs:
  - get
