# permissions for end users to edit cfspaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfspace-editor-role
rules:
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfspaces/status
  verbs:
  - get
