configMapGenerator:
- behavior: merge
  files:
  - controllersconfig/cf_k8s_controllers_config.yaml
  name: config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default
