kpackImageTag: gcr.io/cf-relint-greengrass/korifi-controllers/kpack/beta
clusterBuilderName: cf-kpack-cluster-builder
cfProcessDefaults:
  memoryMB: 1024
  diskQuotaMB: 1024
cfRootNamespace: cf
korifi_controller_namespace: korifi-controllers-system
workloads_tls_secret_name: korifi-workloads-ingress-cert
