
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-workloads-cloudfoundry-org-v1alpha1-cfapp
  failurePolicy: Fail
  name: mcfapp.kb.io
  rules:
  - apiGroups:
    - workloads.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cfapps
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-workloads-cloudfoundry-org-v1alpha1-cfapp
  failurePolicy: Fail
  name: vcfapp.kb.io
  rules:
  - apiGroups:
    - workloads.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cfapps
  sideEffects: None
