apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-kpack-build-serving-cert
spec:
  dnsNames:
  - korifi-kpack-build-webhook-service.{{ .Release.Namespace }}.svc
  - korifi-kpack-build-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: kpack-image-builder-webhook-server-cert
