apiVersion: v1
kind: ConfigMap
metadata:
  name: korifi-kpack-build-config
  namespace: {{ .Release.Namespace }}
data:
  kpack_build_controllers_config.yaml: |
    cfRootNamespace: {{ .Values.global.rootNamespace }}
    clusterBuilderName: {{ default "cf-kpack-cluster-builder" .Values.clusterBuilderName }}
    dropletRepository: {{ .Values.dropletRepository }}
