apiVersion: v1
kind: ConfigMap
metadata:
  name: korifi-kpack-build-config
  namespace: korifi-kpack-build-system
data:
  kpack_build_controllers_config.yaml: |
    cfRootNamespace: {{ .Values.global.rootNamespace }}
    clusterBuilderName: {{ default "cf-kpack-cluster-builder" .Values.clusterBuilderName }}
    kpackImageTag: {{ .Values.packageRegistry }}
