apiVersion: v1
kind: ConfigMap
metadata:
  name: korifi-kpack-build-config
  namespace: {{ .Release.Namespace }}
data:
  kpack_build_controllers_config.yaml: |
    cfRootNamespace: {{ .Values.global.rootNamespace }}
    clusterBuilderName: {{ .Values.clusterBuilderName | default "cf-kpack-cluster-builder" }}
    dropletRepository: {{ .Values.dropletRepository }}
    builderServiceAccount: kpack-service-account
