---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: korifi-kpack-build-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/korifi-kpack-build-serving-cert'
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: korifi-kpack-build-webhook-service
        namespace: '{{ .Release.Namespace }}'
        path: /mutate--v1-pod
    failurePolicy: Ignore
    name: mkpackbuildpod.korifi.cloudfoundry.org
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
    objectSelector:
      matchExpressions:
        - key: kpack.io/build
          operator: Exists
        - key: korifi.cloudfoundry.org/build-workload-name
          operator: Exists
