apiVersion: v1
kind: Service
metadata:
  name: korifi-kpack-build-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: korifi-kpack-image-builder

{{- if .Values.global.debug }}
---
apiVersion: v1
kind: Service
metadata:
  name: korifi-kpack-image-builder-controller-manager-debug-port
spec:
  ports:
  - name: debug-30053
    nodePort: 30053
    port: 30053
    protocol: TCP
    targetPort: 40000
  selector:
    app: korifi-kpack-image-builder
  type: NodePort
{{- end }}
