---
{{- if .Values.debug }}
apiVersion: v1
kind: Service
metadata:
  name: job-task-runner-debug-port
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: debug-30053
      nodePort: 30053
      port: 30053
      protocol: TCP
      targetPort: 40000
  selector:
    app: job-task-runner
  type: NodePort
{{- end }}
