externalFQDN: "api.example.org"
internalPort: 9000

rootNamespace: cf
builderName: kpack-image-builder
defaultLifecycleConfig:
  type: buildpack
  stack: cflinuxfs3
  stagingMemoryMB: 1024
  stagingDiskMB: 1024
packageRegistryBase: gcr.io/cf-relint-greengrass/korifi-controllers/kpack/beta
packageRegistrySecretName: image-registry-credentials # Create this secret in the rootNamespace
defaultDomainName: apps.example.org
