roleMappings:
  admin:
    name: korifi-controllers-admin
    propagate: true
  admin_read_only:
    name: korifi-controllers-admin-read-only
    propagate: true
  cf_user:
    name: korifi-controllers-root-namespace-user
    propagate: false
  global_auditor:
    name: korifi-controllers-global-auditor
    propagate: true
  organization_auditor:
    name: korifi-controllers-organization-auditor
    propagate: false
  organization_billing_manager:
    name: korifi-controllers-organization-billing-manager
    propagate: false
  organization_manager:
    name: korifi-controllers-organization-manager
    propagate: true
  organization_user:
    name: korifi-controllers-organization-user
    propagate: false
  space_auditor:
    name: korifi-controllers-space-auditor
    propagate: false
  space_developer:
    name: korifi-controllers-space-developer
    propagate: false
  space_manager:
    name: korifi-controllers-space-manager
    propagate: false
  space_supporter:
    name: korifi-controllers-space-supporter
    propagate: false
