apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: {{ .Values.global.rootNamespace }}
  annotations:
    cloudfoundry.org/propagate-service-account: "true"
    cloudfoundry.org/propagate-deletion: "false"
    {{- if .Values.global.eksContainerRegistryRoleARN }}
    eks.amazonaws.com/role-arn: {{ .Values.global.eksContainerRegistryRoleARN }}
    {{- end }}
{{- if not .Values.global.eksContainerRegistryRoleARN }}
secrets:
  - name: {{ .Values.global.containerRegistrySecret }}
imagePullSecrets:
  - name: {{ .Values.global.containerRegistrySecret }}
{{- end }}
