# permissions for end users to view cfbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfbuild-viewer-role
rules:
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfbuilds/status
  verbs:
  - get
