# permissions for end users to view cfdroplets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfdroplet-viewer-role
rules:
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfdroplets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfdroplets/status
  verbs:
  - get
