# permissions for end users to edit cfdroplets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfdroplet-editor-role
rules:
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfdroplets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfdroplets/status
  verbs:
  - get
