# permissions for end users to edit cfpackages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfpackage-editor-role
rules:
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfpackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfpackages/status
  verbs:
  - get
