apiVersion: v1
kind: Namespace
metadata:
  name: korifi-gateway
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: korifi-certs
  namespace: {{ .Release.Namespace }}
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: korifi-gateway
  to:
  - group: ""
    kind: Secret
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: korifi
  namespace: korifi-gateway
spec:
  gatewayClassName: {{ .Values.gatewayClass }}
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http-apps
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    hostname: {{ .Values.api.apiServer.url }}
    name: https-api
    port: 443
    protocol: TLS
    tls:
      mode: Passthrough
  - allowedRoutes:
      namespaces:
        from: All
    hostname: "*.{{ .Values.defaultAppDomainName }}"
    name: https-apps
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: korifi-workloads-ingress-cert
        namespace: {{ .Release.Namespace }}
      mode: Terminate
---
kind: TLSRoute
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: korifi-api
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: korifi
    namespace: korifi-gateway
  hostnames:
  - {{ .Values.api.apiServer.url }}
  rules:
  - backendRefs:
    - kind: Service
      name: korifi-api-svc
      port: 443
