# The CF Root Namespace User
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: root-namespace-user
rules:
  - apiGroups:
      - networking.cloudfoundry.org
    resources:
      - cfdomains
    verbs:
      - get
      - list
