# The CF Space Auditor Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: space-auditor
rules:
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfapps
  verbs:
  - get
  - list

- apiGroups:
  - kpack.io
  resources:
  - clusterbuilders
  verbs:
  - get
