global:
  rootNamespace: cf
  debug: false
  packageRegistrySecret: image-registry-credentials

include: true
namespace: korifi-kpack-build-system
replicas: 1
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 100Mi

image: cloudfoundry/korifi-kpack-image-builder:latest

packageRegistry: registry-org/package-repo-name
clusterBuilderName: cf-kpack-cluster-builder
exampleClusterBuilder:
  create: false
  kpackBuilderRegistry: registry-org/kpack-builder-repo-name
