global:
  rootNamespace: cf
  debug: false
  containerRegistrySecret: image-registry-credentials

include: true
replicas: 1
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 100Mi

image: cloudfoundry/korifi-kpack-image-builder:latest

dropletRepository:
clusterBuilderName:
clusterStackBuildImage: paketobuildpacks/build:full-cnb
clusterStackRunImage: paketobuildpacks/run:full-cnb
builderRepository:
