global:
  rootNamespace: cf
  debug: false
  packageRegistrySecret: image-registry-credentials

include: true
replicas: 1
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 100Mi

image: cloudfoundry/korifi-kpack-image-builder:latest

dropletRepositoryPrefix: index.docker.io/my-dockerhub-username
# clusterBuilderName:
builderRepository: index.docker.io/my-dockerhub-username/kpack-builder
