global:
  rootNamespace: cf
  debug: false
  packageRegistrySecret: image-registry-credentials

include: true
namespace: korifi-kpack-build-system
replicas: 1
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 100Mi

image: cloudfoundry/korifi-kpack-image-builder:latest

dropletRegistry: registry-org/droplet-repo-name
clusterBuilderName:
builderRegistry: registry-org/kpack-builder-repo-name
