---
# Defines a build for the provided package. Triggers the staging process which results in a runnable container image.
# Successful CF Builds automatically receive CF Droplets.
apiVersion: workloads.cloudfoundry.org/v1alpha1
kind: CFBuild
metadata:
  # apps.cloudfoundry.org/ labels are all managed by a mutating webhook
  labels:
    apps.cloudfoundry.org/appGuid: 14dcda7d-1fa1-4a91-b437-fbdba20e8c5a
    apps.cloudfoundry.org/packageGuid: ac85ad52-f52f-48e3-8c99-5e7badbe79c5
  name: 1591ee05-e208-4cf3-a662-1c2da42f20a7
spec:
  appRef:
    name: 14dcda7d-1fa1-4a91-b437-fbdba20e8c5a
  packageRef:
    name: ac85ad52-f52f-48e3-8c99-5e7badbe79c5
  lifecycle:
    type: buildpack
    data:
      buildpacks: []
      stack: cflinuxfs3
