apiVersion: v1
kind: ConfigMap
metadata:
  name: korifi-controllers-config
data:
  korifi_controllers_config.yaml: |-
    builderName: {{ .Values.reconcilers.build }}
    runnerName: {{ .Values.reconcilers.app }}
    cfProcessDefaults:
      memoryMB: {{ .Values.processDefaults.memoryMB }}
      diskQuotaMB: {{ .Values.processDefaults.diskQuotaMB }}
    cfRootNamespace: {{ .Values.global.rootNamespace }}
    packageRegistrySecretName: {{ .Values.global.packageRegistrySecret }}
    taskTTL: {{ .Values.taskTTL }}
    workloads_tls_secret_name: {{ .Values.workloadsTLSSecret.name }}
    workloads_tls_secret_namespace: {{ .Release.Namespace }}
