apiVersion: v1
kind: ConfigMap
metadata:
  name: korifi-controllers-config
  namespace: {{ .Release.Namespace }}
data:
  korifi_controllers_config.yaml: |-
    builderName: {{ .Values.reconcilers.build }}
    runnerName: {{ .Values.reconcilers.app }}
    cfProcessDefaults:
      memoryMB: {{ .Values.processDefaults.memoryMB }}
      diskQuotaMB: {{ .Values.processDefaults.diskQuotaMB }}
    cfRootNamespace: {{ .Values.global.rootNamespace }}
    {{- if not .Values.global.eksContainerRegistryRoleARN }}
    containerRegistrySecretName: {{ .Values.global.containerRegistrySecret | quote }}
    {{- end }}
    taskTTL: {{ .Values.taskTTL }}
    workloads_tls_secret_name: {{ .Values.workloadsTLSSecret }}
    workloads_tls_secret_namespace: {{ .Release.Namespace }}
    namespaceLabels:
    {{- range $key, $value := .Values.namespaceLabels }}
      {{ $key }}: {{ $value }}
    {{- end }}
