{{- if .Values.global.generateIngressCertificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-workloads-ingress-cert
spec:
  commonName: \*.{{ .Values.global.defaultAppDomainName }}
  dnsNames:
  - \*.{{ .Values.global.defaultAppDomainName }}
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: korifi-workloads-ingress-cert
{{- end}}
