global:
  rootNamespace: cf
  debug: false
  defaultAppDomainName: apps.my-cf-domain.com
  generateIngressCertificates: false
  containerRegistrySecret: image-registry-credentials
  eksContainerRegistryRoleARN: ""

include: true
replicas: 1
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 100Mi

image: cloudfoundry/korifi-controllers:latest
reconcilers:
  build: kpack-image-builder
  app: statefulset-runner
processDefaults:
  memoryMB: 1024
  diskQuotaMB: 1024
taskTTL: 30d
workloadsTLSSecret: korifi-workloads-ingress-cert
