apiVersion: v1
kind: ConfigMap
metadata:
  name: korifi-controllers-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    includeKpackImageBuilder: {{ .Values.kpackImageBuilder.include }}
    includeJobTaskRunner: {{ .Values.jobTaskRunner.include }}
    includeStatefulsetRunner: {{ .Values.statefulsetRunner.include }}
    includeContourRouter: {{ .Values.contourRouter.include }}
    builderName: {{ .Values.global.reconcilers.build }}
    runnerName: {{ .Values.global.reconcilers.run }}
    cfProcessDefaults:
      memoryMB: {{ .Values.controllers.processDefaults.memoryMB }}
      diskQuotaMB: {{ .Values.controllers.processDefaults.diskQuotaMB }}
    cfRootNamespace: {{ .Values.global.rootNamespace }}
    {{- if not .Values.global.eksContainerRegistryRoleARN }}
    {{- if .Values.global.containerRegistrySecrets }}
    containerRegistrySecretNames:
    {{- range .Values.global.containerRegistrySecrets }}
    - {{ . | quote }}
    {{- end }}
    {{- else }}
    containerRegistrySecretNames:
    - {{ .Values.global.containerRegistrySecret | quote }}
    {{- end }}
    {{- end }}
    taskTTL: {{ .Values.controllers.taskTTL }}
    workloads_tls_secret_name: {{ .Values.controllers.workloadsTLSSecret }}
    workloads_tls_secret_namespace: {{ .Release.Namespace }}
    namespaceLabels:
    {{- range $key, $value := .Values.controllers.namespaceLabels }}
      {{ $key }}: {{ $value }}
    {{- end }}
    extraVCAPApplicationValues:
    {{- $defaultDict := dict "cf_api" (printf "https://%s" .Values.api.apiServer.url) -}}
    {{- range $key, $value := merge .Values.controllers.extraVCAPApplicationValues $defaultDict }}
      {{ $key }}: {{ $value }}
    {{- end }}
    maxRetainedPackagesPerApp: {{ .Values.controllers.maxRetainedPackagesPerApp }}
    maxRetainedBuildsPerApp: {{ .Values.controllers.maxRetainedBuildsPerApp }}
    logLevel: {{ .Values.global.logLevel }}
    {{- if .Values.kpackImageBuilder.include }}
    clusterBuilderName: {{ .Values.kpackImageBuilder.clusterBuilderName | default "cf-kpack-cluster-builder" }}
    builderReadinessTimeout: {{ required "builderReadinessTimeout is required" .Values.kpackImageBuilder.builderReadinessTimeout }}
    containerRepositoryPrefix: {{ .Values.global.containerRepositoryPrefix | quote }}
    builderServiceAccount: kpack-service-account
    cfStagingResources:
      buildCacheMB: {{ .Values.api.lifecycle.stagingRequirements.buildCacheMB }}
      diskMB: {{ .Values.api.lifecycle.stagingRequirements.diskMB }}
      memoryMB: {{ .Values.api.lifecycle.stagingRequirements.memoryMB }}
    {{- if .Values.global.eksContainerRegistryRoleARN }}
    containerRegistryType: "ECR"
    {{- end }}
    {{- end }}
    {{- if .Values.jobTaskRunner.include }}
    jobTTL: {{ required "jobTTL is required" .Values.jobTaskRunner.jobTTL }}
    {{- end }}
