global:
  rootNamespace: cf
  debug: false

include: true
namespace: korifi-job-task-runner-system
replicas: 1
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

image: cloudfoundry/korifi-job-task-runner:latest
jobTTL: 24h
