---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: cloudfoundry/korifi-api:latest
  path: .
  docker:
    buildx:
      file: api/Dockerfile
      rawOptions: ["--build-arg", "version=v9999.99.99-local.dev"]

- image: cloudfoundry/korifi-controllers:latest
  path: .
  docker:
    buildx:
      file: controllers/Dockerfile
      rawOptions: ["--build-arg", "version=v9999.99.99-local.dev"]
