---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: cloudfoundry/korifi-api:latest
  path: .
  docker:
    buildx:
      file: api/remote-debug/Dockerfile

- image: cloudfoundry/korifi-controllers:latest
  path: .
  docker:
    buildx:
      file: controllers/remote-debug/Dockerfile
