adminUserName: cf-admin

global:
  defaultAppDomainName: apps-127-0-0-1.nip.io
  generateIngressCertificates: true
  logLevel: debug

api:
  apiServer:
    url: localhost
  image: cloudfoundry/korifi-api:latest
  lifecycle:
    stagingRequirements:
      buildCacheMB: 1024


controllers:
  taskTTL: 5s
  image: cloudfoundry/korifi-controllers:latest

jobTaskRunner:
  jobTTL: 5s

kpackImageBuilder:
  clusterStackBuildImage: paketobuildpacks/build:base-cnb
  clusterStackRunImage: paketobuildpacks/run:base-cnb
