adminUserName: cf-admin
defaultAppDomainName: apps-127-0-0-1.nip.io
generateIngressCertificates: true
logLevel: debug
stagingRequirements:
  buildCacheMB: 1024

api:
  apiServer:
    url: localhost
  image: cloudfoundry/korifi-api:latest


controllers:
  taskTTL: 5s
  image: cloudfoundry/korifi-controllers:latest

jobTaskRunner:
  jobTTL: 5s

kpackImageBuilder:
  clusterStackID: io.buildpacks.stacks.jammy
  clusterStackBuildImage: paketobuildpacks/build-jammy-base
  clusterStackRunImage: paketobuildpacks/run-jammy-base
