# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/workloads.cloudfoundry.org_cfapps.yaml
- bases/workloads.cloudfoundry.org_cfpackages.yaml
- bases/workloads.cloudfoundry.org_cfprocesses.yaml
- bases/workloads.cloudfoundry.org_cfbuilds.yaml
- bases/networking.cloudfoundry.org_cfroutes.yaml
- bases/networking.cloudfoundry.org_cfdomains.yaml
- bases/services.cloudfoundry.org_cfserviceinstances.yaml
- bases/services.cloudfoundry.org_cfservicebindings.yaml
- bases/workloads.cloudfoundry.org_cforgs.yaml
- bases/workloads.cloudfoundry.org_cfspaces.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_cfapps.yaml
- patches/webhook_in_cfpackages.yaml
- patches/webhook_in_cfprocesses.yaml
- patches/webhook_in_cfbuilds.yaml
- patches/webhook_in_cfroutes.yaml
- patches/webhook_in_cfdomains.yaml
#- patches/webhook_in_cfserviceinstances.yaml
#- patches/webhook_in_cfservicebindings.yaml
#- patches/webhook_in_cforgs.yaml
#- patches/webhook_in_cfspaces.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_cfapps.yaml
- patches/cainjection_in_cfpackages.yaml
- patches/cainjection_in_cfprocesses.yaml
- patches/cainjection_in_cfbuilds.yaml
- patches/cainjection_in_cfroutes.yaml
- patches/cainjection_in_cfdomains.yaml
#- patches/cainjection_in_cfserviceinstances.yaml
#- patches/cainjection_in_cfservicebindings.yaml
#- patches/cainjection_in_cforgs.yaml
#- patches/cainjection_in_cfspaces.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
