# permissions for end users to edit runworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runworkload-editor-role
rules:
- apiGroups:
  - ext.cloudfoundry.org
  resources:
  - runworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ext.cloudfoundry.org
  resources:
  - runworkloads/status
  verbs:
  - get
