name: Adds all new issues to the Icebox column in our backlog project

on:
  issues:
    types:
      - opened

jobs:
  add-to-backlog:
    if: "!contains(github.event.issue.labels.*.name, 'epic')"
    name: Add issue to backlog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.6.0
        with:
          project-url: https://github.com/orgs/cloudfoundry/projects/35
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
  add-to-roadmap:
    if: contains(github.event.issue.labels.*.name, 'epic')
    name: Add epic to roadmap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.6.0
        with:
          project-url: https://github.com/orgs/cloudfoundry/projects/29
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
