name: Test, Build, and Push image from main

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
    - '.*'

jobs:
  run-envtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      
      - name: Run envtest
        run: make test

  build:
    needs: run-envtest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: cloudfoundry/cf-k8s-controllers:latest
