apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- name: mkpackbuildpod.korifi.cloudfoundry.org
  objectSelector:
    matchExpressions:
      - key: kpack.io/build
        operator: Exists
      - key: korifi.cloudfoundry.org/build-workload-name
        operator: Exists
